#!/bin/bash

USER=$((id -u))

if [ $USER -ne 0 ]; then
    echo "ERROR:: Please run this script with root privelege"
fi

dnf install mysql -y

if [ $? -ne 0 ]; then
    echo "ERROR:: failure"
else
    echo " success"
fi